### ISSUE TITLE
Support expanded view when using find on messages

### ISSUE THREAD

**Issue by pfista** [nylas/nylas-ruby#189]
If I wanted to get a specific message using the expadned view to see the message id header, I'm unable to do so because find doesn't support constraints or views:

```
puts client.messages.expanded.find(msg[:id]).to_h[:headers][:message_id]
```

`headers` here will always be nil

**Comment by dem** [comment]
@pfista as per current code of `Model` there is no way to fetch expanded view on any model instance, using `reload` or `find` methods. For temporarily solution we used monkey patching:
```
class Nylas::Message
  def expanded
    return self unless headers.nil?

    assign(api.execute(method: :get, path: resource_path, query: { view: 'expanded' }))
    self
  end
end
```

And it become possible to fetch single expanded message in way it was in 3.x version:
`puts client.messages.find(msg[:id]).expanded.headers.message_id`

It is not optimal because of 2 calls to nylas api, but should work.

**Comment by bmulholland** [comment]
This just caught me. Would be really nice if we could do `nylas.messages.expanded.find` just like `nylas.meessages.expanded.where`. More documentation on using expanded views in Ruby would be great, too.
