### ISSUE TITLE
Support for`include_types` filter option for deltas 

### ISSUE THREAD

**Issue by marcelotto** [nylas/nylas-ruby#202]
It seems this was already tackled in a couple of PRs and finally got merged with #131. In the latest version (4.2.4) however, this feature seems to be no longer present. What happened? Is it possible to get this back?

**Comment by BenLloydPearson** [comment]
Hi @marcelotto thank you for bringing this up! The functionality you are looking for was moved to the nylas-streaming gem because it contains a dependency that is pretty large: https://rubygems.org/gems/nylas-streaming

Unfortunately, this gem is running on an old version of our SDK, so it may or may not work for you. We are currently working to bring this functionality into the main nylas gem again as a separate release tag so it can be made available one again. I'll let you know when the work is complete.

**Comment by BenLloydPearson** [comment]
This feature should be available via the nylas-streaming package. To use it, simply replace `gem install nylas` with `gem install nylas-streaming`. We made this separation so that you only need to download the large dependencies for the streaming functionality if you need the feature.
