### ISSUE TITLE
Update in drafts - File_ids getting overwritten

### ISSUE THREAD

**Issue by bhattjay** [nylas/nylas-ruby#94]
If your current version of draft already has some files uploaded and is saved, and now if you first of all find this draft, and then make a change in any other field, then this new version overwrites the existing file_ids of the existing draft. It passes over an empty array in the update, and hence, you lose out on the already saved files.

**Comment by zspencer** [comment]
@bhattjay - This has been resolved in 4.0, as we have added an `update` method which only sends the change data instead of all the attributes. Save may still exhibit this behavior, but I would hope we can add dirty-checking at some point.

If the problem persists beyond once upgrading to 4.X please re-open this ticket.
